backup:
  backup_dir: data/backup
  files:
    departments: data/backup/departments.avro
    hired_employees: data/backup/hired_employees.avro
    jobs: data/backup/jobs.avro
csv:
  departments:
    columns:
    - id
    - department
    path: data/sources/departments.csv
  hired_employees:
    columns:
    - id
    - name
    - datetime
    - department_id
    - job_id
    path: data/sources/hired_employees.csv
  jobs:
    columns:
    - id
    - job
    path: data/sources/jobs.csv
database:
  dbname: challenge_database
  host: postgres
  password: challenge_password
  port: 5432
  user: challenge_user
logs:
  path: data/logs
