csv:
  hired_employees:
    path: "./data/sources/hired_employees.csv"
    columns: ["id", "name", "datetime", "department_id", "job_id"]
  departments:
    path: "./data/sources/departments.csv"
    columns: ["id", "department"]
  jobs:
    path: "./data/sources/jobs.csv"
    columns: ["id", "job"]

database:
  host: "postgres"
  port: 5432
  user: "challenge_user"
  password: "challenge_password"
  dbname: "challenge_database"
