version: '3.8'

services:
  app:
    build: .
    container_name: challenge_api_fastapi
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - CONFIG_PATH=/app/config.yaml
      - SECRET_KEY=6q2Qy3P9L3e8Fv9s-Qb7kW7lqv2Sx9V1fR3TzU7q2P7L3e8Fv7sQb7kW7lqv2Sx7
    volumes:
      - ./:/app

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: challenge_user
      POSTGRES_PASSWORD: challenge_password
      POSTGRES_DB: challenge_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
